# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Web Dev Notes
email: jlouzado@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Joel Louzado and these are my study notes and some thoughts collected along my journey toward becoming a front-end developer.
baseurl: # the subpath of your site, e.g. /blog
url: "https://jlouzado.github.io/webdev-notes/" # the base hostname & protocol for your site
twitter_username: jlouzado 
github_username:  jlouzado 

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics: 
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
